<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('property_premises_sec', function (Blueprint $table) {
            $table->id();
            $table->foreignId('property_id')->constrained('property_section')->onDelete('cascade');                
            $table->text('sec2_premises_no')->nullable();                
            $table->text('sec2_street_address')->nullable();                
            $table->text('sec2_building_no')->nullable();                
            $table->text('sec2_building_desc')->nullable();                
            $table->text('sec2_r1_sub_insure')->nullable();                
            $table->text('sec2_r1_amount')->nullable();                
            $table->text('sec2_r1_coins')->nullable();                
            $table->text('sec2_r1_valuation')->nullable();                
            $table->text('sec2_r1_cause_loss')->nullable();                
            $table->text('sec2_r1_inflation')->nullable();                
            $table->text('sec2_r1_ded')->nullable();                
            $table->text('sec2_r1_ded_type')->nullable();                
            $table->text('sec2_r1_blanket')->nullable();                
            $table->text('sec2_r1_forms')->nullable();    
            $table->text('sec2_r2_sub_insure')->nullable();                
            $table->text('sec2_r2_amount')->nullable();                
            $table->text('sec2_r2_coins')->nullable();                
            $table->text('sec2_r2_valuation')->nullable();                
            $table->text('sec2_r2_cause_loss')->nullable();                
            $table->text('sec2_r2_inflation')->nullable();                
            $table->text('sec2_r2_ded')->nullable();                
            $table->text('sec2_r2_ded_type')->nullable();                
            $table->text('sec2_r2_blanket')->nullable();                
            $table->text('sec2_r2_forms')->nullable(); 
            $table->text('sec2_r3_sub_insure')->nullable();                
            $table->text('sec2_r3_amount')->nullable();                
            $table->text('sec2_r3_coins')->nullable();                
            $table->text('sec2_r3_valuation')->nullable();                
            $table->text('sec2_r3_cause_loss')->nullable();                
            $table->text('sec2_r3_inflation')->nullable();                
            $table->text('sec2_r3_ded')->nullable();                
            $table->text('sec2_r3_ded_type')->nullable();                
            $table->text('sec2_r3_blanket')->nullable();                
            $table->text('sec2_r3_forms')->nullable(); 
            $table->text('sec2_r4_sub_insure')->nullable();                
            $table->text('sec2_r4_amount')->nullable();                
            $table->text('sec2_r4_coins')->nullable();                
            $table->text('sec2_r4_valuation')->nullable();                
            $table->text('sec2_r4_cause_loss')->nullable();                
            $table->text('sec2_r4_inflation')->nullable();                
            $table->text('sec2_r4_ded')->nullable();                
            $table->text('sec2_r4_ded_type')->nullable();                
            $table->text('sec2_r4_blanket')->nullable();                
            $table->text('sec2_r4_forms')->nullable(); 
            $table->text('sec2_r5_sub_insure')->nullable();                
            $table->text('sec2_r5_amount')->nullable();                
            $table->text('sec2_r5_coins')->nullable();                
            $table->text('sec2_r5_valuation')->nullable();                
            $table->text('sec2_r5_cause_loss')->nullable();                
            $table->text('sec2_r5_inflation')->nullable();                
            $table->text('sec2_r5_ded')->nullable();                
            $table->text('sec2_r5_ded_type')->nullable();                
            $table->text('sec2_r5_blanket')->nullable();                
            $table->text('sec2_r5_forms')->nullable(); 
            $table->text('sec2_business_income')->nullable();                
            $table->text('sec2_value_reporting')->nullable();                
            $table->text('sec2_spoilage')->nullable();                
            $table->text('sec2_property_coverageDes')->nullable();                
            $table->text('sec2_limit')->nullable();                
            $table->text('sec2_agreement')->nullable();                
            $table->text('sec2_breakdown')->nullable();                
            $table->text('sec2_power_outage')->nullable();                
            $table->text('sec2_selling_price')->nullable();                
            $table->text('sec2_deductable')->nullable();                
            $table->text('sec2_coverage_accept')->nullable();                
            $table->text('sec2_coverage_reject')->nullable();                
            $table->text('sec2_coverage_limit')->nullable();                
            $table->text('sec2_mine_accept')->nullable();                
            $table->text('sec2_mine_reject')->nullable();                
            $table->text('sec2_mine_limit')->nullable();                
            $table->text('sec2_propertyHistorical')->nullable();                
            $table->text('sec2_slidesStruct')->nullable();                
            $table->text('sec2_construction_ty')->nullable();                
            $table->text('sec2_distanceto')->nullable();                
            $table->text('sec2_fireState')->nullable();                
            $table->text('sec2_fire_district')->nullable();                
            $table->text('sec2_code_no')->nullable();                
            $table->text('sec2_protCl')->nullable();                
            $table->text('sec2_stories')->nullable();                
            $table->text('sec2_basm')->nullable();                
            $table->text('sec2_yrbuilt')->nullable();                
            $table->text('sec2_totalArea')->nullable();                
            $table->text('sec2_wiringYr')->nullable();                
            $table->text('sec2_plumbering')->nullable();                
            $table->text('sec2_roofingYr')->nullable();                
            $table->text('sec2_heating')->nullable();                
            $table->text('sec2_otherYR')->nullable();                
            $table->text('sec2_otherYRField')->nullable();                
            $table->text('sec2_resistive')->nullable();                
            $table->text('sec2_semi_resistive')->nullable();                
            $table->text('sec2_roofT_otherCheck')->nullable();                
            $table->text('sec2_roofT_otherCheckField')->nullable();                
            $table->text('sec2_headingSource')->nullable();                
            $table->text('sec2_dateInstalled')->nullable();                
            $table->text('sec2_primary_boiler')->nullable();                
            $table->text('sec2_primary_solidFuel')->nullable();                
            $table->text('sec2_primary_otherC')->nullable();                
            $table->text('sec2_primary_otherCF')->nullable();                
            $table->text('sec2_PrimarybolierPlace')->nullable();                
            $table->text('sec2_secondary_boiler')->nullable();                
            $table->text('sec2_secondary_solidFuel')->nullable();                
            $table->text('sec2_secondary_otherC')->nullable();                
            $table->text('sec2_secondary_otherCF')->nullable();                
            $table->text('sec2_secondarybolierPlace')->nullable();                
            $table->text('sec2_rightExp')->nullable();                
            $table->text('sec2_leftExp')->nullable();                
            $table->text('sec2_frontExp')->nullable();                
            $table->text('sec2_rearExp')->nullable();                
            $table->text('sec2_buglerAlarm')->nullable();                
            $table->text('sec2_certificate')->nullable();                
            $table->text('sec2_expirationDate')->nullable();                
            $table->text('sec2_centralSatation')->nullable();                
            $table->text('sec2_localGong')->nullable();                
            $table->text('sec2_withKeys')->nullable();                
            $table->text('sec2_burglerAlarmInstall')->nullable();                
            $table->text('sec2_extent')->nullable();                
            $table->text('sec2_grade')->nullable();                
            $table->text('sec2_watchman')->nullable();                
            $table->text('sec2_clockHourly')->nullable();                
            $table->text('sec2_otherCheckCH')->nullable();                
            $table->text('sec2_otherCheckCHF')->nullable();
            $table->text('sec2_premisisFireProtect')->nullable();                
            $table->text('sec2_sprik')->nullable();                
            $table->text('sec2_fireAlarmManufacture')->nullable();                
            $table->text('sec2_CentralS')->nullable();                
            $table->text('sec2_localG')->nullable();                
            $table->text('acc2rdCheck')->nullable();                
            $table->text('sec2_lenderPay')->nullable();                
            $table->text('sec2_lossPayee')->nullable();                
            $table->text('sec2_mortgagee')->nullable();                
            $table->text('sec2_intrestOther')->nullable();                
            $table->text('sec2_intrestOtherField')->nullable();                
            $table->text('sec2_nameAddress')->nullable();                
            $table->text('sec2_rank')->nullable();                
            $table->text('sec2_evidence')->nullable();                
            $table->text('sec2_certificate_intrest')->nullable();                
            $table->text('sec2_referenceLoan')->nullable();                
            $table->text('sec2_location_interest')->nullable();                
            $table->text('sec2_building_interest')->nullable();                
            $table->text('sec2_itemClass_interest')->nullable();                
            $table->text('sec2_item_interest')->nullable();                
            $table->text('sec2_itemDescriptionInt')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('property_premises_sec');
    }
};
