<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('commercial_insurance_applications', function (Blueprint $table) {
            $table->id();
            $table->foreignId('client_id')->constrained('clients')->onDelete('cascade');
            $table->text('application_date')->nullable();
            $table->text('agency_name')->nullable();
            $table->text('agency_address')->nullable();
            $table->text('agency_city')->nullable();
            $table->text('agency_state')->nullable();
            $table->text('agency_zipcode')->nullable();
            $table->text('agency_contact_name')->nullable();
            $table->text('agency_contact_phone_no')->nullable();
            $table->text('agency_contact_fax_no')->nullable();
            $table->text('agency_contact_email')->nullable();
            $table->text('agency_code')->nullable();
            $table->text('agency_sub_code')->nullable();
            $table->text('agency_customer_id')->nullable();
            $table->text('carrier')->nullable();
            $table->text('naic_code')->nullable();
            $table->text('program_name')->nullable();
            $table->text('program_code')->nullable();
            $table->text('policy_number')->nullable();
            $table->text('under_writer')->nullable();
            $table->text('under_writer_office')->nullable();
            $table->text('status_quote')->nullable();
            $table->text('status_issue_policy')->nullable();
            $table->text('status_renew')->nullable();
            $table->text('status_bound')->nullable();
            $table->text('status_change')->nullable();
            $table->text('status_cancel')->nullable();
            $table->text('status_date')->nullable();
            $table->text('status_time')->nullable();
            $table->text('status_time_type')->nullable();
            $table->text('boiler_machinery')->nullable();
            $table->text('boiler_machinery_premium_one')->nullable();
            $table->text('boiler_machinery_cyber_privacy')->nullable();
            $table->text('boiler_machinery_premium_two')->nullable();
            $table->text('boiler_machinery_yacht')->nullable();
            $table->text('boiler_machinery_premium_three')->nullable();
            $table->text('business_auto')->nullable();
            $table->text('business_auto_premium_one')->nullable();
            $table->text('business_auto_fiduciary')->nullable();
            $table->text('business_auto_premium_two')->nullable();
            $table->text('business_auto_yacht_one')->nullable();
            $table->text('business_auto_yacht_one_field')->nullable();
            $table->text('business_auto_premium_three')->nullable();
            $table->text('business_owner')->nullable();
            $table->text('business_owner_premium_one')->nullable();
            $table->text('business_owner_garage')->nullable();
            $table->text('business_owner_premium_two')->nullable();
            $table->text('business_owner_yacht_two')->nullable();
            $table->text('business_owner_yacht_two_field')->nullable();
            $table->text('business_owner_premium_three')->nullable();
            $table->text('business_commercial_gl')->nullable();
            $table->text('business_commercial_gl_premium_one')->nullable();
            $table->text('business_commercial_gl_liquor')->nullable();
            $table->text('business_commercial_gl_premium_two')->nullable();
            $table->text('business_commercial_gl_yacht_three')->nullable();
            $table->text('business_commercial_gl_yacht_three_field')->nullable();
            $table->text('business_commercial_gl_premium_three')->nullable();
            $table->text('business_inland')->nullable();
            $table->text('business_inland_premium_one')->nullable();
            $table->text('business_inland_motor')->nullable();
            $table->text('business_inland_premium_two')->nullable();
            $table->text('business_inland_yacht_four')->nullable();
            $table->text('business_inland_yacht_four_field')->nullable();
            $table->text('business_inland_premium_three')->nullable();
            $table->text('commercial_property')->nullable();
            $table->text('commercial_property_premium_one')->nullable();
            $table->text('commercial_property_trucker')->nullable();
            $table->text('commercial_property_premium_two')->nullable();
            $table->text('commercial_property_yacht_five')->nullable();
            $table->text('commercial_property_yacht_five_field')->nullable();
            $table->text('commercial_property_premium_three')->nullable();
            $table->text('crime')->nullable();
            $table->text('crime_premium_one')->nullable();
            $table->text('crime_umbrella')->nullable();
            $table->text('crime_yacht_six')->nullable();
            $table->text('crime_yacht_six_field')->nullable();
            $table->text('crime_premium_three')->nullable();
            $table->text('attachment_accounts_receivable')->nullable();
            $table->text('attachment_glass_sign')->nullable();
            $table->text('attachment_statement')->nullable();
            $table->text('attachment_additional_interest')->nullable();
            $table->text('attachment_hotel')->nullable();
            $table->text('attachment_state_supplement')->nullable();
            $table->text('attachment_addition_premises')->nullable();
            $table->text('attachment_installation_risk')->nullable();
            $table->text('attachment_vacant_building')->nullable();
            $table->text('attachment_appartment_building')->nullable();
            $table->text('attachment_international_liability')->nullable();
            $table->text('attachment_vehicle_schedule')->nullable();
            $table->text('attachment_condo_assn')->nullable();
            $table->text('attachment_internation_property_exposer')->nullable();
            $table->text('attachment_default_check_one')->nullable();
            $table->text('attachment_default_check_one_field')->nullable();
            $table->text('attachment_contractors_supplement')->nullable();
            $table->text('attachment_loss_summary')->nullable();
            $table->text('attachment_default_check_two')->nullable();
            $table->text('attachment_default_check_two_field')->nullable();
            $table->text('attachment_coverages_schedule')->nullable();
            $table->text('attachment_open_cargo_section')->nullable();
            $table->text('attachment_default_check_three')->nullable();
            $table->text('attachment_default_check_three_field')->nullable();
            $table->text('attachment_dealers_section')->nullable();
            $table->text('attachment_premium_payment')->nullable();
            $table->text('attachment_default_check_four')->nullable();
            $table->text('attachment_default_check_four_field')->nullable();
            $table->text('attachment_driver_infomation')->nullable();
            $table->text('attachment_professional_liability')->nullable();
            $table->text('attachment_default_check_five')->nullable();
            $table->text('attachment_default_check_five_field')->nullable();
            $table->text('attachment_electronic_data')->nullable();
            $table->text('attachment_restauratt')->nullable();
            $table->text('attachment_default_check_six')->nullable();
            $table->text('attachment_default_check_six_field')->nullable();
            $table->text('policy_proposed_eff_date')->nullable();
            $table->text('policy_proposed_exp_date')->nullable();
            $table->text('policy_billing_plan')->nullable();
            $table->text('policy_payment_plan')->nullable();
            $table->text('policy_method_of_payment')->nullable();
            $table->text('policy_audit')->nullable();
            $table->text('policy_deposit')->nullable();
            $table->text('policy_minimum_premium')->nullable();
            $table->text('policy_premium')->nullable();           
            $table->foreignId('created_by')->constrained('users')->onDelete('cascade');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('commercial_insurance_applications');
    }
};