<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('installation_builder_risk_section', function (Blueprint $table) {
            $table->id();
            $table->foreignId('client_id')->constrained('clients')->onDelete('cascade');
            $table->text('invoice_date')->nullable();
            $table->text('agency_name')->nullable();
            $table->text('career')->nullable();
            $table->text('naic_code')->nullable();
            $table->text('policy_number')->nullable();
            $table->text('effective_date')->nullable();
            $table->text('name_insured')->nullable();
            $table->text('insallationCheck')->nullable();
            $table->text('buildingRiskCheck')->nullable();
            $table->text('limit_sing_loc')->nullable();
            $table->text('limit_per_disaster')->nullable();
            $table->text('limit_temp_loc')->nullable();
            $table->text('transit_limit')->nullable();
            $table->text('earthQuakeCheck')->nullable();
            $table->text('earthQuakeSubLimit')->nullable();
            $table->text('earthQuakeDeductible')->nullable();
            $table->text('flood')->nullable();
            $table->text('floodSubLimit')->nullable();
            $table->text('floodDeductible')->nullable();
            $table->text('otherCauseCheck')->nullable();
            $table->text('otherCauseField')->nullable();
            $table->text('otherCauseSubLim')->nullable();
            $table->text('otherCauseDeductible')->nullable();
            $table->text('specialCause')->nullable();
            $table->text('specialCauseSubLim')->nullable();
            $table->text('specialCauseDeductible')->nullable();
            $table->text('broadCause')->nullable();
            $table->text('basicSubLim')->nullable();
            $table->text('broadDeductible')->nullable();
            $table->text('operationTerritory')->nullable();
            $table->text('pastMonth')->nullable();
            $table->text('nextMonth')->nullable();
            $table->text('resi_annualNum')->nullable();
            $table->text('resi_duration')->nullable();
            $table->text('resi_max')->nullable();
            $table->text('resi_avg')->nullable();
            $table->text('resi_maxCost')->nullable();
            $table->text('resi_minCost')->nullable();
            $table->text('resi_avgCost')->nullable();
            $table->text('resi_materialPerc')->nullable();
            $table->text('commercial_annualNum')->nullable();
            $table->text('commercial_duration')->nullable();
            $table->text('commercial_max')->nullable();
            $table->text('commercial_avg')->nullable();
            $table->text('commercial_maxCost')->nullable();
            $table->text('commercial_minCost')->nullable();
            $table->text('commercial_avgCost')->nullable();
            $table->text('commercial_materialPerc')->nullable();
            $table->text('accordCheck')->nullable();
            $table->text('sec1_Lender')->nullable();
            $table->text('sec1_LienHolder')->nullable();
            $table->text('sec1_LossPayee')->nullable();
            $table->text('sec1_otherCheck')->nullable();
            $table->text('sec1_otherCheckField')->nullable();
            $table->text('sec1_nameAddress')->nullable();
            $table->text('sec1_rank')->nullable();
            $table->text('sec1_referenceNo')->nullable();
            $table->text('sec1_certificateReq')->nullable();
            $table->text('sec1_loc')->nullable();
            $table->text('sec1_building')->nullable();
            $table->text('sec1_scheduledItem')->nullable();
            $table->text('sec1_intrestOther')->nullable();
            $table->text('sec1_description')->nullable();
            $table->text('sec2_Lender')->nullable();
            $table->text('sec2_LienHolder')->nullable();
            $table->text('sec2_LossPayee')->nullable();
            $table->text('sec2_otherCheck')->nullable();
            $table->text('sec2_otherCheckField')->nullable();
            $table->text('sec2_nameAddress')->nullable();
            $table->text('sec2_rank')->nullable();
            $table->text('sec2_referenceNo')->nullable();
            $table->text('sec2_certificateReq')->nullable();
            $table->text('sec2_loc')->nullable();
            $table->text('sec2_building')->nullable();
            $table->text('sec2_scheduledItem')->nullable();
            $table->text('sec2_intrestOther')->nullable();
            $table->text('sec2_description')->nullable();
            $table->text('sec3_Lender')->nullable();
            $table->text('sec3_LienHolder')->nullable();
            $table->text('sec3_LossPayee')->nullable();
            $table->text('sec3_otherCheck')->nullable();
            $table->text('sec3_otherCheckField')->nullable();
            $table->text('sec3_nameAddress')->nullable();
            $table->text('sec3_rank')->nullable();
            $table->text('sec3_referenceNo')->nullable();
            $table->text('sec3_certificateReq')->nullable();
            $table->text('sec3_loc')->nullable();
            $table->text('sec3_building')->nullable();
            $table->text('sec3_scheduledItem')->nullable();
            $table->text('sec3_intrestOther')->nullable();
            $table->text('sec3_description')->nullable();
            $table->text('riggingHosting')->nullable();
            $table->text('estimatePercentagRigging')->nullable();
            $table->text('jobsiteSecurity')->nullable();
            $table->text('remarks')->nullable();
            $table->text('p2_limit_loc')->nullable();
            $table->text('p2_limit_temp_loc')->nullable();
            $table->text('p2_transit_limit')->nullable();
            $table->text('p2_earthQuake')->nullable();
            $table->text('p2_earthQuakeSubLim')->nullable();
            $table->text('p2_earthQuakeDeductible')->nullable();
            $table->text('p2_FLOOD')->nullable();
            $table->text('p2_FLOODSubLim')->nullable();
            $table->text('p2_FLOODDeductible')->nullable();
            $table->text('p2_otherCauseCheck')->nullable();
            $table->text('p2_otherCauseCheckField')->nullable();
            $table->text('p2_otherCauseSubLim')->nullable();
            $table->text('p2_otherCauseDeductible')->nullable();
            $table->text('p2_Special')->nullable();
            $table->text('p2_SpecialSubLim')->nullable();
            $table->text('p2_SpecialDeductible')->nullable();
            $table->text('p2_BROAD')->nullable();
            $table->text('p2_BASIC')->nullable();
            $table->text('p2_BASICDeductible')->nullable();
            $table->text('p2_commencement')->nullable();
            $table->text('p2_completion')->nullable();
            $table->text('p2_contractAmount')->nullable();
            $table->text('p2_ownerSupplied')->nullable();
            $table->text('p2_jobSecurity')->nullable();
            $table->text('p2_workedPerformed')->nullable();
            $table->text('p2_insuredJobNumber')->nullable();

            $table->text('p2_sec1_Lender')->nullable();
            $table->text('p2_sec1_LienHolder')->nullable();
            $table->text('p2_sec1_LossPayee')->nullable();
            $table->text('p2_sec1_otherCheck')->nullable();
            $table->text('p2_sec1_otherCheckField')->nullable();
            $table->text('p2_sec1_nameAddress')->nullable();
            $table->text('p2_sec1_rank')->nullable();
            $table->text('p2_sec1_referenceNo')->nullable();
            $table->text('p2_sec1_certificateReq')->nullable();
            $table->text('p2_sec1_loc')->nullable();
            $table->text('p2_sec1_building')->nullable();
            $table->text('p2_sec1_scheduledItem')->nullable();
            $table->text('p2_sec1_intrestOther')->nullable();
            $table->text('p2_sec1_description')->nullable();
            $table->text('p2_sec2_Lender')->nullable();
            $table->text('p2_sec2_LienHolder')->nullable();
            $table->text('p2_sec2_LossPayee')->nullable();
            $table->text('p2_sec2_otherCheck')->nullable();
            $table->text('p2_sec2_otherCheckField')->nullable();
            $table->text('p2_sec2_nameAddress')->nullable();
            $table->text('p2_sec2_rank')->nullable();
            $table->text('p2_sec2_referenceNo')->nullable();
            $table->text('p2_sec2_certificateReq')->nullable();
            $table->text('p2_sec2_loc')->nullable();
            $table->text('p2_sec2_building')->nullable();
            $table->text('p2_sec2_scheduledItem')->nullable();
            $table->text('p2_sec2_intrestOther')->nullable();
            $table->text('p2_sec2_description')->nullable();
            $table->text('p2_sec3_Lender')->nullable();
            $table->text('p2_sec3_LienHolder')->nullable();
            $table->text('p2_sec3_LossPayee')->nullable();
            $table->text('p2_sec3_otherCheck')->nullable();
            $table->text('p2_sec3_otherCheckField')->nullable();
            $table->text('p2_sec3_nameAddress')->nullable();
            $table->text('p2_sec3_rank')->nullable();
            $table->text('p2_sec3_referenceNo')->nullable();
            $table->text('p2_sec3_certificateReq')->nullable();
            $table->text('p2_sec3_loc')->nullable();
            $table->text('p2_sec3_building')->nullable();
            $table->text('p2_sec3_scheduledItem')->nullable();
            $table->text('p2_sec3_intrestOther')->nullable();
            $table->text('p2_sec3_description')->nullable();
            $table->text('P2_amountShipped')->nullable();
            $table->text('P2_applicatsVehcles')->nullable();
            $table->text('P2_contractorCarrier')->nullable();
            $table->text('P2_distanceInvolved')->nullable();
            $table->text('p2_riggingHosting')->nullable();
            $table->text('p2_remarks')->nullable();
            $table->text('agency_id')->nullable();
            $table->text('P2_producerSignature')->nullable();
            $table->text('P2_producerName')->nullable();
            $table->text('P2_producerLicense')->nullable();
            $table->text('P2_applicantSignature')->nullable();
            $table->text('P2_applicationdate')->nullable();
            $table->text('P2_nationalProducerNo')->nullable();                 
            $table->foreignId('created_by')->constrained('users')->onDelete('cascade');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('installation_builder_risk_section');
    }
};
