<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('dwelling_option_coverage', function (Blueprint $table) {
            $table->id();
            $table->foreignId('dwelling_fire_id')->constrained('dwelling_fire_application')->onDelete('cascade');
            $table->text('agencyID')->nullable();
            $table->text('includedRisk')->nullable();
            $table->text('risk_amount')->nullable();
            $table->text('risk_prem')->nullable();
            $table->text('coverageInc')->nullable();
            $table->text('risk_premium')->nullable();
            $table->text('colaps_included')->nullable();
            $table->text('colaps_covpremium')->nullable();
            $table->text('colaps_premium')->nullable();
            $table->text('colaps_percentageIncrease')->nullable();
            $table->text('colaps_perm')->nullable();
            $table->text('loss_ass')->nullable();
            $table->text('loss_assPrem')->nullable();
            $table->text('lawCov_agg')->nullable();
            $table->text('lawCov_incr')->nullable();
            $table->text('lawCov_prem')->nullable();
            $table->text('lawCov_limt')->nullable();
            $table->text('lawCov_const')->nullable();
            $table->text('ordIncluded')->nullable();
            $table->text('lawCov_rebild')->nullable();
            $table->text('derbs_included')->nullable();
            $table->text('derbs_limit')->nullable();
            $table->text('derbs_prem')->nullable();
            $table->text('derbs_inc')->nullable();
            $table->text('derbs_unit')->nullable();
            $table->text('derbs_unitPrem')->nullable();
            $table->text('earth_ded')->nullable();
            $table->text('earth_terr')->nullable();
            $table->text('earth_prem')->nullable();
            $table->text('earth_dedAmount')->nullable();
            $table->text('earth_type')->nullable();
            $table->text('dreinIncluded')->nullable();
            $table->text('dreinLimit')->nullable();
            $table->text('dreinPrem')->nullable();
            $table->text('massVaneerAmount')->nullable();
            $table->text('windYes')->nullable();
            $table->text('code_sec1_opts')->nullable();
            $table->text('code_sec1_limit')->nullable();
            $table->text('code_sec1_appl')->nullable();
            $table->text('code_sec1_deduct')->nullable();
            $table->text('code_sec1_prem')->nullable();
            $table->text('code_sec1_opts2')->nullable();
            $table->text('code_sec1_limit2')->nullable();
            $table->text('code_sec1_appl2')->nullable();
            $table->text('code_sec1_deduct2')->nullable();
            $table->text('code_sec1_prem2')->nullable();
            $table->text('desc_sec1_opt')->nullable();
            $table->text('desc_sec1_limit')->nullable();
            $table->text('desc_sec1_appl')->nullable();
            $table->text('desc_sec1_type')->nullable();
            $table->text('desc_sec1_opt2')->nullable();
            $table->text('desc_sec1_limit2')->nullable();
            $table->text('desc_sec1_appl2')->nullable();
            $table->text('desc_sec1_type2')->nullable();
            $table->text('desc_sec1_tree')->nullable();
            $table->text('desc_sec1_y')->nullable();
            $table->text('desc_sec1_tree2')->nullable();
            $table->text('desc_sec1_y2')->nullable();
            $table->text('code_sec2_opts')->nullable();
            $table->text('code_sec2_limit')->nullable();
            $table->text('code_sec2_appl')->nullable();
            $table->text('code_sec2_deduct')->nullable();
            $table->text('code_sec2_prem')->nullable();
            $table->text('code_sec2_opts2')->nullable();
            $table->text('code_sec2_limit2')->nullable();
            $table->text('code_sec2_appl2')->nullable();
            $table->text('code_sec2_deduct2')->nullable();
            $table->text('code_sec2_prem2')->nullable();
            $table->text('desc_sec2_opt')->nullable();
            $table->text('desc_sec2_limit')->nullable();
            $table->text('desc_sec2_appl')->nullable();
            $table->text('desc_sec2_type')->nullable();
            $table->text('desc_sec2_opt2')->nullable();
            $table->text('desc_sec2_limit2')->nullable();
            $table->text('desc_sec2_appl2')->nullable();
            $table->text('desc_sec2_type2')->nullable();
            $table->text('desc_sec2_tree')->nullable();
            $table->text('desc_sec2_y')->nullable();
            $table->text('desc_sec2_tree2')->nullable();
            $table->text('desc_sec2_y2')->nullable();
            $table->text('code_sec3_opts')->nullable();
            $table->text('code_sec3_limit')->nullable();
            $table->text('code_sec3_appl')->nullable();
            $table->text('code_sec3_deduct')->nullable();
            $table->text('code_sec3_prem')->nullable();
            $table->text('code_sec3_opts2')->nullable();
            $table->text('code_sec3_limit2')->nullable();
            $table->text('code_sec3_appl2')->nullable();
            $table->text('code_sec3_deduct2')->nullable();
            $table->text('code_sec3_prem2')->nullable();
            $table->text('desc_sec3_opt')->nullable();
            $table->text('desc_sec3_limit')->nullable();
            $table->text('desc_sec3_appl')->nullable();
            $table->text('desc_sec3_type')->nullable();
            $table->text('desc_sec3_opt2')->nullable();
            $table->text('desc_sec3_limit2')->nullable();
            $table->text('desc_sec3_appl2')->nullable();
            $table->text('desc_sec3_type2')->nullable();
            $table->text('desc_sec3_tree')->nullable();
            $table->text('desc_sec3_y')->nullable();
            $table->text('desc_sec3_tree2')->nullable();
            $table->text('desc_sec3_y2')->nullable();
            $table->text('code_sec4_opts')->nullable();
            $table->text('code_sec4_limit')->nullable();
            $table->text('code_sec4_appl')->nullable();
            $table->text('code_sec4_deduct')->nullable();
            $table->text('code_sec4_prem')->nullable();
            $table->text('code_sec4_opts2')->nullable();
            $table->text('code_sec4_limit2')->nullable();
            $table->text('code_sec4_appl2')->nullable();
            $table->text('code_sec4_deduct2')->nullable();
            $table->text('code_sec4_prem2')->nullable();
            $table->text('desc_sec4_opt')->nullable();
            $table->text('desc_sec4_limit')->nullable();
            $table->text('desc_sec4_appl')->nullable();
            $table->text('desc_sec4_type')->nullable();
            $table->text('desc_sec4_opt2')->nullable();
            $table->text('desc_sec4_limit2')->nullable();
            $table->text('desc_sec4_appl2')->nullable();
            $table->text('desc_sec4_type2')->nullable();
            $table->text('desc_sec4_tree')->nullable();
            $table->text('desc_sec4_y')->nullable();
            $table->text('desc_sec4_tree2')->nullable();
            $table->text('desc_sec4_y2')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('dwelling_option_coverage');
    }
};
