<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('property_premises', function (Blueprint $table) {
            $table->id();
            $table->foreignId('property_id')->constrained('property_section')->onDelete('cascade');
            $table->text('sec1_premises_no')->nullable();                
            $table->text('sec1_street_address')->nullable();                
            $table->text('sec1_building_no')->nullable();                
            $table->text('sec1_building_desc')->nullable();                
            $table->text('sec1_r1_sub_insure')->nullable();                
            $table->text('sec1_r1_amount')->nullable();                
            $table->text('sec1_r1_coins')->nullable();                
            $table->text('sec1_r1_valuation')->nullable();                
            $table->text('sec1_r1_cause_loss')->nullable();                
            $table->text('sec1_r1_inflation')->nullable();                
            $table->text('sec1_r1_ded')->nullable();                
            $table->text('sec1_r1_ded_type')->nullable();                
            $table->text('sec1_r1_blanket')->nullable();                
            $table->text('sec1_r1_forms')->nullable();    
            $table->text('sec1_r2_sub_insure')->nullable();                
            $table->text('sec1_r2_amount')->nullable();                
            $table->text('sec1_r2_coins')->nullable();                
            $table->text('sec1_r2_valuation')->nullable();                
            $table->text('sec1_r2_cause_loss')->nullable();                
            $table->text('sec1_r2_inflation')->nullable();                
            $table->text('sec1_r2_ded')->nullable();                
            $table->text('sec1_r2_ded_type')->nullable();                
            $table->text('sec1_r2_blanket')->nullable();                
            $table->text('sec1_r2_forms')->nullable(); 
            $table->text('sec1_r3_sub_insure')->nullable();                
            $table->text('sec1_r3_amount')->nullable();                
            $table->text('sec1_r3_coins')->nullable();                
            $table->text('sec1_r3_valuation')->nullable();                
            $table->text('sec1_r3_cause_loss')->nullable();                
            $table->text('sec1_r3_inflation')->nullable();                
            $table->text('sec1_r3_ded')->nullable();                
            $table->text('sec1_r3_ded_type')->nullable();                
            $table->text('sec1_r3_blanket')->nullable();                
            $table->text('sec1_r3_forms')->nullable(); 
            $table->text('sec1_r4_sub_insure')->nullable();                
            $table->text('sec1_r4_amount')->nullable();                
            $table->text('sec1_r4_coins')->nullable();                
            $table->text('sec1_r4_valuation')->nullable();                
            $table->text('sec1_r4_cause_loss')->nullable();                
            $table->text('sec1_r4_inflation')->nullable();                
            $table->text('sec1_r4_ded')->nullable();                
            $table->text('sec1_r4_ded_type')->nullable();                
            $table->text('sec1_r4_blanket')->nullable();                
            $table->text('sec1_r4_forms')->nullable(); 
            $table->text('sec1_r5_sub_insure')->nullable();                
            $table->text('sec1_r5_amount')->nullable();                
            $table->text('sec1_r5_coins')->nullable();                
            $table->text('sec1_r5_valuation')->nullable();                
            $table->text('sec1_r5_cause_loss')->nullable();                
            $table->text('sec1_r5_inflation')->nullable();                
            $table->text('sec1_r5_ded')->nullable();                
            $table->text('sec1_r5_ded_type')->nullable();                
            $table->text('sec1_r5_blanket')->nullable();                
            $table->text('sec1_r5_forms')->nullable(); 
            $table->text('sec1_business_income')->nullable();                
            $table->text('sec1_value_reporting')->nullable();                
            $table->text('sec1_spoilage')->nullable();                
            $table->text('sec1_property_coverageDes')->nullable();                
            $table->text('sec1_limit')->nullable();                
            $table->text('sec1_agreement')->nullable();                
            $table->text('sec1_breakdown')->nullable();                
            $table->text('sec1_power_outage')->nullable();                
            $table->text('sec1_selling_price')->nullable();                
            $table->text('sec1_deductable')->nullable();                
            $table->text('sec1_coverage_accept')->nullable();                
            $table->text('sec1_coverage_reject')->nullable();                
            $table->text('sec1_coverage_limit')->nullable();                
            $table->text('sec1_mine_accept')->nullable();                
            $table->text('sec1_mine_reject')->nullable();                
            $table->text('sec1_mine_limit')->nullable();                
            $table->text('sec1_propertyHistorical')->nullable();                
            $table->text('sec1_slidesStruct')->nullable();                
            $table->text('sec1_construction_ty')->nullable();                
            $table->text('sec1_distanceto')->nullable();                
            $table->text('sec1_fireState')->nullable();                
            $table->text('sec1_fire_district')->nullable();                
            $table->text('sec1_code_no')->nullable();                
            $table->text('sec1_protCl')->nullable();                
            $table->text('sec1_stories')->nullable();                
            $table->text('sec1_basm')->nullable();                
            $table->text('sec1_yrbuilt')->nullable();                
            $table->text('sec1_totalArea')->nullable();                
            $table->text('sec1_wiringYr')->nullable();                
            $table->text('sec1_plumbering')->nullable();                
            $table->text('sec1_roofingYr')->nullable();                
            $table->text('sec1_heating')->nullable();                
            $table->text('sec1_otherYR')->nullable();                
            $table->text('sec1_otherYRField')->nullable();                
            $table->text('sec1_resistive')->nullable();                
            $table->text('sec1_semi_resistive')->nullable();                
            $table->text('sec1_roofT_otherCheck')->nullable();                
            $table->text('sec1_roofT_otherCheckField')->nullable();                
            $table->text('sec1_headingSource')->nullable();                
            $table->text('sec1_dateInstalled')->nullable();                
            $table->text('sec1_primary_boiler')->nullable();                
            $table->text('sec1_primary_solidFuel')->nullable();                
            $table->text('sec1_primary_otherC')->nullable();                
            $table->text('sec1_primary_otherCF')->nullable();                
            $table->text('sec1_PrimarybolierPlace')->nullable();                
            $table->text('sec1_secondary_boiler')->nullable();                
            $table->text('sec1_secondary_solidFuel')->nullable();                
            $table->text('sec1_secondary_otherC')->nullable();                
            $table->text('sec1_secondary_otherCF')->nullable();                
            $table->text('sec1_secondarybolierPlace')->nullable();                
            $table->text('sec1_rightExp')->nullable();                
            $table->text('sec1_leftExp')->nullable();                
            $table->text('sec1_frontExp')->nullable();                
            $table->text('sec1_rearExp')->nullable();                
            $table->text('sec1_buglerAlarm')->nullable();                
            $table->text('sec1_certificate')->nullable();                
            $table->text('sec1_expirationDate')->nullable();                
            $table->text('sec1_centralSatation')->nullable();                
            $table->text('sec1_localGong')->nullable();                
            $table->text('sec1_withKeys')->nullable();                
            $table->text('sec1_burglerAlarmInstall')->nullable();                
            $table->text('sec1_extent')->nullable();                
            $table->text('sec1_grade')->nullable();                
            $table->text('sec1_watchman')->nullable();                
            $table->text('sec1_clockHourly')->nullable();                
            $table->text('sec1_otherCheckCH')->nullable();                
            $table->text('sec1_otherCheckCHF')->nullable();
            $table->text('sec1_premisisFireProtect')->nullable();                
            $table->text('sec1_sprik')->nullable();                
            $table->text('sec1_fireAlarmManufacture')->nullable();                
            $table->text('sec1_CentralS')->nullable();                
            $table->text('sec1_localG')->nullable();                
            $table->text('accordCheck')->nullable();                
            $table->text('sec1_lenderPay')->nullable();                
            $table->text('sec1_lossPayee')->nullable();                
            $table->text('sec1_mortgagee')->nullable();                
            $table->text('sec1_intrestOther')->nullable();                
            $table->text('sec1_intrestOtherField')->nullable();                
            $table->text('sec1_nameAddress')->nullable();                
            $table->text('sec1_rank')->nullable();                
            $table->text('sec1_evidence')->nullable();                
            $table->text('sec1_certificate_intrest')->nullable();                
            $table->text('sec1_referenceLoan')->nullable();                
            $table->text('sec1_location_interest')->nullable();                
            $table->text('sec1_building_interest')->nullable();                
            $table->text('sec1_itemClass_interest')->nullable();                
            $table->text('sec1_item_interest')->nullable();                
            $table->text('sec1_itemDescriptionInt')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('property_premises');
    }
};
