<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('cia_application_info', function (Blueprint $table) {
            $table->id();
            $table->foreignId('commerical_appId')->constrained('commercial_insurance_applications')->onDelete('cascade');
            $table->text('appication_info_one_name')->nullable();
            $table->text('appication_info_one_address')->nullable();
            $table->text('appication_info_one_city')->nullable();
            $table->text('appication_info_one_state')->nullable();
            $table->text('appication_info_one_zip')->nullable();
            $table->text('appication_info_one_gl_code')->nullable();
            $table->text('appication_info_one_SIC')->nullable();
            $table->text('appication_info_one_NAICS')->nullable();
            $table->text('appication_info_one_FEIN')->nullable();
            $table->text('appication_info_one_business_phone')->nullable();
            $table->text('appication_info_one_website')->nullable();
            $table->text('appication_info_one_corporation')->nullable();
            $table->text('appication_info_one_joint_venture')->nullable();
            $table->text('appication_info_one_not_for_profilt')->nullable();
            $table->text('appication_info_one_subchapter')->nullable();
            $table->text('appication_info_one_individual')->nullable();
            $table->text('appication_info_one_llc_check')->nullable();
            $table->text('appication_info_one_llc_check_field')->nullable();
            $table->text('appication_info_one_partnership')->nullable();
            $table->text('appication_info_one_trust')->nullable();
            $table->text('appication_info_two_name')->nullable();
            $table->text('appication_info_two_address')->nullable();
            $table->text('appication_info_two_city')->nullable();
            $table->text('appication_info_two_state')->nullable();
            $table->text('appication_info_two_zip')->nullable();
            $table->text('appication_info_two_gl_code')->nullable();
            $table->text('appication_info_two_SIC')->nullable();
            $table->text('appication_info_two_NAICS')->nullable();
            $table->text('appication_info_two_FEIN')->nullable();
            $table->text('appication_info_two_business_phone')->nullable();
            $table->text('appication_info_two_website')->nullable();
            $table->text('appication_info_two_corporation')->nullable();
            $table->text('appication_info_two_joint_venture')->nullable();
            $table->text('appication_info_two_not_for_profilt')->nullable();
            $table->text('appication_info_two_subchapter')->nullable();
            $table->text('appication_info_two_individual')->nullable();
            $table->text('appication_info_two_llc_check')->nullable();
            $table->text('appication_info_two_llc_check_field')->nullable();
            $table->text('appication_info_two_partnership')->nullable();
            $table->text('appication_info_two_trust')->nullable();
            $table->text('appication_info_three_name')->nullable();
            $table->text('appication_info_three_address')->nullable();
            $table->text('appication_info_three_city')->nullable();
            $table->text('appication_info_three_state')->nullable();
            $table->text('appication_info_three_zip')->nullable();
            $table->text('appication_info_three_gl_code')->nullable();
            $table->text('appication_info_three_SIC')->nullable();
            $table->text('appication_info_three_NAICS')->nullable();
            $table->text('appication_info_three_FEIN')->nullable();
            $table->text('appication_info_three_business_phone')->nullable();
            $table->text('appication_info_three_website')->nullable();
            $table->text('appication_info_three_corporation')->nullable();
            $table->text('appication_info_three_joint_venture')->nullable();
            $table->text('appication_info_three_not_for_profilt')->nullable();
            $table->text('appication_info_three_subchapter')->nullable();
            $table->text('appication_info_three_individual')->nullable();
            $table->text('appication_info_three_llc_check')->nullable();
            $table->text('appication_info_three_llc_check_field')->nullable();
            $table->text('appication_info_three_partnership')->nullable();
            $table->text('appication_info_three_trust')->nullable();
            $table->text('contact_info_c_type_one')->nullable();
            $table->text('contact_info_c_type_two')->nullable();
            $table->text('contact_info_name_one')->nullable();
            $table->text('contact_info_name_two')->nullable();
            $table->text('contact_info_primary_one')->nullable();
            $table->text('contact_info_secondary_one')->nullable();
            $table->text('contact_info_primary_two')->nullable();
            $table->text('contact_info_secondary_two')->nullable();
            $table->text('contact_info_primary_email_one')->nullable();
            $table->text('contact_info_secondary_email_one')->nullable();
            $table->text('contact_info_primary_email_two')->nullable();
            $table->text('prem_info_s1_r1_loc')->nullable();
            $table->text('prem_info_s1_r1_street')->nullable();
            $table->text('prem_info_s1_r1_ftEmployee')->nullable();
            $table->text('prem_info_s1_r1_annual_rev')->nullable();
            $table->text('prem_info_s1_r1_inside')->nullable();
            $table->text('prem_info_s1_r1_owner')->nullable();
            $table->text('prem_info_s1_r1_occupied_area')->nullable();
            $table->text('prem_info_s1_r2_bld')->nullable();
            $table->text('prem_info_s1_r2_city')->nullable();
            $table->text('prem_info_s1_r2_state')->nullable();
            $table->text('prem_info_s1_r2_outside')->nullable();
            $table->text('prem_info_s1_r2_tenant')->nullable();
            $table->text('prem_info_s1_r2_partTEmp')->nullable();
            $table->text('prem_info_s1_r2_pubArea')->nullable();
            $table->text('prem_info_s1_r2_country')->nullable();
            $table->text('prem_info_s1_r2_zip')->nullable();
            $table->text('prem_info_s1_r2_otherCheck_one')->nullable();
            $table->text('prem_info_s1_r2_otherCheckField_one')->nullable();
            $table->text('prem_info_s1_r2_otherCheck_two')->nullable();
            $table->text('prem_info_s1_r2_otherCheckField_two')->nullable();
            $table->text('prem_info_s1_r2_totalBArea')->nullable();
            $table->text('prem_info_s1_description')->nullable();
            $table->text('prem_info_s1_leased')->nullable();
            $table->text('prem_info_s2_r1_loc')->nullable();
            $table->text('prem_info_s2_r1_street')->nullable();
            $table->text('prem_info_s2_r1_ftEmployee')->nullable();
            $table->text('prem_info_s2_r1_annual_rev')->nullable();
            $table->text('prem_info_s2_r1_inside')->nullable();
            $table->text('prem_info_s2_r1_owner')->nullable();
            $table->text('prem_info_s2_r1_occupied_area')->nullable();
            $table->text('prem_info_s2_r2_bld')->nullable();
            $table->text('prem_info_s2_r2_city')->nullable();
            $table->text('prem_info_s2_r2_state')->nullable();
            $table->text('prem_info_s2_r2_outside')->nullable();
            $table->text('prem_info_s2_r2_tenant')->nullable();
            $table->text('prem_info_s2_r2_partTEmp')->nullable();
            $table->text('prem_info_s2_r2_pubArea')->nullable();
            $table->text('prem_info_s2_r2_country')->nullable();
            $table->text('prem_info_s2_r2_zip')->nullable();
            $table->text('prem_info_s2_r2_otherCheck_one')->nullable();
            $table->text('prem_info_s2_r2_otherCheckField_one')->nullable();
            $table->text('prem_info_s2_r2_otherCheck_two')->nullable();
            $table->text('prem_info_s2_r2_otherCheckField_two')->nullable();
            $table->text('prem_info_s2_r2_totalBArea')->nullable();
            $table->text('prem_info_s2_description')->nullable();
            $table->text('prem_info_s2_leased')->nullable();
            $table->text('prem_info_s3_r1_loc')->nullable();
            $table->text('prem_info_s3_r1_street')->nullable();
            $table->text('prem_info_s3_r1_ftEmployee')->nullable();
            $table->text('prem_info_s3_r1_annual_rev')->nullable();
            $table->text('prem_info_s3_r1_inside')->nullable();
            $table->text('prem_info_s3_r1_owner')->nullable();
            $table->text('prem_info_s3_r1_occupied_area')->nullable();
            $table->text('prem_info_s3_r2_bld')->nullable();
            $table->text('prem_info_s3_r2_city')->nullable();
            $table->text('prem_info_s3_r2_state')->nullable();
            $table->text('prem_info_s3_r2_outside')->nullable();
            $table->text('prem_info_s3_r2_tenant')->nullable();
            $table->text('prem_info_s3_r2_partTEmp')->nullable();
            $table->text('prem_info_s3_r2_pubArea')->nullable();
            $table->text('prem_info_s3_r2_country')->nullable();
            $table->text('prem_info_s3_r2_zip')->nullable();
            $table->text('prem_info_s3_r2_otherCheck_one')->nullable();
            $table->text('prem_info_s3_r2_otherCheckField_one')->nullable();
            $table->text('prem_info_s3_r2_otherCheck_two')->nullable();
            $table->text('prem_info_s3_r2_otherCheckField_two')->nullable();
            $table->text('prem_info_s3_r2_totalBArea')->nullable();
            $table->text('prem_info_s3_description')->nullable();
            $table->text('prem_info_s3_leased')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cia_application_info');
    }
};
