<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ciaApplicationInfo extends Model
{
     use  HasFactory;

    protected $table = 'cia_application_info';

    protected $fillable = [
        'commerical_appId',
        'appication_info_one_name',
        'appication_info_one_address',
        'appication_info_one_city',
        'appication_info_one_state',
        'appication_info_one_zip',
        'appication_info_one_gl_code',
        'appication_info_one_SIC',
        'appication_info_one_NAICS',
        'appication_info_one_FEIN',
        'appication_info_one_business_phone',
        'appication_info_one_website',
        'appication_info_one_corporation',
        'appication_info_one_joint_venture',
        'appication_info_one_not_for_profilt',
        'appication_info_one_subchapter',
        'appication_info_one_individual',
        'appication_info_one_llc_check',
        'appication_info_one_llc_check_field',
        'appication_info_one_partnership',
        'appication_info_one_trust',
        'appication_info_two_name',
        'appication_info_two_address',
        'appication_info_two_city',
        'appication_info_two_state',
        'appication_info_two_zip',
        'appication_info_two_gl_code',
        'appication_info_two_SIC',
        'appication_info_two_NAICS',
        'appication_info_two_FEIN',
        'appication_info_two_business_phone',
        'appication_info_two_website',
        'appication_info_two_corporation',
        'appication_info_two_joint_venture',
        'appication_info_two_not_for_profilt',
        'appication_info_two_subchapter',
        'appication_info_two_individual',
        'appication_info_two_llc_check',
        'appication_info_two_llc_check_field',
        'appication_info_two_partnership',
        'appication_info_two_trust',
        'appication_info_three_name',
        'appication_info_three_address',
        'appication_info_three_city',
        'appication_info_three_state',
        'appication_info_three_zip',
        'appication_info_three_gl_code',
        'appication_info_three_SIC',
        'appication_info_three_NAICS',
        'appication_info_three_FEIN',
        'appication_info_three_business_phone',
        'appication_info_three_website',
        'appication_info_three_corporation',
        'appication_info_three_joint_venture',
        'appication_info_three_not_for_profilt',
        'appication_info_three_subchapter',
        'appication_info_three_individual',
        'appication_info_three_llc_check',
        'appication_info_three_llc_check_field',
        'appication_info_three_partnership',
        'appication_info_three_trust',
        'contact_info_c_type_one',
        'contact_info_c_type_two',
        'contact_info_name_one',
        'contact_info_name_two',
        'contact_info_primary_one',
        'contact_info_secondary_one',
        'contact_info_primary_two',
        'contact_info_secondary_two',
        'contact_info_primary_email_one',
        'contact_info_secondary_email_one',
        'contact_info_primary_email_two',
        'prem_info_s1_r1_loc',
        'prem_info_s1_r1_street',
        'prem_info_s1_r1_ftEmployee',
        'prem_info_s1_r1_annual_rev',
        'prem_info_s1_r1_inside',
        'prem_info_s1_r1_owner',
        'prem_info_s1_r1_occupied_area',
        'prem_info_s1_r2_bld',
        'prem_info_s1_r2_city',
        'prem_info_s1_r2_state',
        'prem_info_s1_r2_outside',
        'prem_info_s1_r2_tenant',
        'prem_info_s1_r2_partTEmp',
        'prem_info_s1_r2_pubArea',
        'prem_info_s1_r2_country',
        'prem_info_s1_r2_zip',
        'prem_info_s1_r2_otherCheck_one',
        'prem_info_s1_r2_otherCheckField_one',
        'prem_info_s1_r2_otherCheck_two',
        'prem_info_s1_r2_otherCheckField_two',
        'prem_info_s1_r2_totalBArea',
        'prem_info_s1_description',
        'prem_info_s1_leased',
        'prem_info_s2_r1_loc',
        'prem_info_s2_r1_street',
        'prem_info_s2_r1_ftEmployee',
        'prem_info_s2_r1_annual_rev',
        'prem_info_s2_r1_inside',
        'prem_info_s2_r1_owner',
        'prem_info_s2_r1_occupied_area',
        'prem_info_s2_r2_bld',
        'prem_info_s2_r2_city',
        'prem_info_s2_r2_state',
        'prem_info_s2_r2_outside',
        'prem_info_s2_r2_tenant',
        'prem_info_s2_r2_partTEmp',
        'prem_info_s2_r2_pubArea',
        'prem_info_s2_r2_country',
        'prem_info_s2_r2_zip',
        'prem_info_s2_r2_otherCheck_one',
        'prem_info_s2_r2_otherCheckField_one',
        'prem_info_s2_r2_otherCheck_two',
        'prem_info_s2_r2_otherCheckField_two',
        'prem_info_s2_r2_totalBArea',
        'prem_info_s2_description',
        'prem_info_s2_leased',
        'prem_info_s3_r1_loc',
        'prem_info_s3_r1_street',
        'prem_info_s3_r1_ftEmployee',
        'prem_info_s3_r1_annual_rev',
        'prem_info_s3_r1_inside',
        'prem_info_s3_r1_owner',
        'prem_info_s3_r1_occupied_area',
        'prem_info_s3_r2_bld',
        'prem_info_s3_r2_city',
        'prem_info_s3_r2_state',
        'prem_info_s3_r2_outside',
        'prem_info_s3_r2_tenant',
        'prem_info_s3_r2_partTEmp',
        'prem_info_s3_r2_pubArea',
        'prem_info_s3_r2_country',
        'prem_info_s3_r2_zip',
        'prem_info_s3_r2_otherCheck_one',
        'prem_info_s3_r2_otherCheckField_one',
        'prem_info_s3_r2_otherCheck_two',
        'prem_info_s3_r2_otherCheckField_two',
        'prem_info_s3_r2_totalBArea',
        'prem_info_s3_description',
        'prem_info_s3_leased',
    ];

    public function application(): BelongsTo
    {
        return $this->belongsTo(CommercialInsuranceApplication::class, 'commerical_appId');
    }
}
