<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ciaBusiness extends Model
{
    use  HasFactory;

    protected $table = 'cia_business';

    protected $fillable = [
        'commerical_appId',
        'natureB_apartments',
        'natureB_contractor',
        'natureB_manufacturing',
        'natureB_restaurant',
        'natureB_service',
        'natureB_otherCheck',
        'natureB_otherCheck_field',
        'natureB_dateBusiness',
        'natureB_condomin',
        'natureB_institutional',
        'natureB_office',
        'natureB_retail',
        'natureB_wholesale',
        'natureB_primary_description',
        'natureB_retailStore',
        'natureB_installationService',
        'natureB_premisesInstallation',
        'natureB_operationDescription',
        'addit_nameAddress',
        'addit_Rank',
        'addit_additionalInsured',
        'addit_beachWarranty',
        'addit_coOwner',
        'addit_employeeLessor',
        'addit_leasebackOwner',
        'addit_lenderLoss',
        'addit_otherCheck',
        'addit_otherCheckField',
        'addit_lienholder',
        'addit_lossPayee',
        'addit_mortgagee',
        'addit_owner',
        'addit_registrant',
        'addit_trustee',
        'addit_eviCertificate',
        'addit_eviPolicy',
        'addit_eviSendBill',
        'addit_reference',
        'addit_location',
        'addit_building',
        'addit_vehicle',
        'addit_boat',
        'addit_airport',
        'addit_aircraft',
        'addit_itemclass',
        'addit_item',
        'addit_itemDescription',
        'addit_refLoan',
        'addit_interestEDate',
        'addit_lienAmount',
        'addit_phone',
        'addit_fax',
        'addit_reasonFInterest',
        'addit_emailAdd',
        'generalInfo_q1A_parentCompany',
        'generalInfo_q1A_Relationship',
        'generalInfo_q1A_owned',
        'generalInfo_q1B_parentCompany',
        'generalInfo_q1B_Relationship',
        'generalInfo_q1B_owned',
        'generalInfo_q2',
        'generalInfo_q3_explosive',
        'generalInfo_q4_t1r1_lBusiness',
        'generalInfo_q4_t1r1_policy',
        'generalInfo_q4_t1r2_lBusiness',
        'generalInfo_q4_t1r2_policy',
        'generalInfo_q4_t2r1_lBusiness',
        'generalInfo_q4_t2r1_policy',
        'generalInfo_q4_t2r2_lBusiness',
        'generalInfo_q4_t2r2_policy',
        'generalInfo_q5',
        'generalInfo_q6',
        'generalInfo_q7',
        'generalInfo_q8_r1_occurDate',
        'generalInfo_q8_r1_explanation',
        'generalInfo_q8_r1_resolution',
        'generalInfo_q8_r1_resolveDate',
        'generalInfo_q8_r2_occurDate',
        'generalInfo_q8_r2_explanation',
        'generalInfo_q8_r2_resolution',
        'generalInfo_q8_r2_resolveDate',
        'generalInfo_q9_r1_occurDate',
        'generalInfo_q9_r1_explanation',
        'generalInfo_q9_r1_resolution',
        'generalInfo_q9_r1_resolveDate',
        'generalInfo_q9_r2_occurDate',
        'generalInfo_q9_r2_explanation',
        'generalInfo_q9_r2_resolution',
        'generalInfo_q9_r2_resolveDate',
        'generalInfo_q10_r1_occurDate',
        'generalInfo_q10_r1_explanation',
        'generalInfo_q10_r1_resolution',
        'generalInfo_q10_r1_resolveDate',
        'generalInfo_q10_r2_occurDate',
        'generalInfo_q10_r2_explanation',
        'generalInfo_q10_r2_resolution',
        'generalInfo_q10_r2_resolveDate',
        'generalInfo_q11',
        'generalInfo_q12',
        'generalInfo_q13',
        'generalInfo_q14',
        'generalInfo_q15',
        'agencyID',
    ];

    public function application(): BelongsTo
    {
        return $this->belongsTo(CommercialInsuranceApplication::class, 'commerical_appId');
    }
}
