<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class dwelling_option_coverage extends Model
{
    use  HasFactory;

    protected $table = 'dwelling_option_coverage';

    protected $fillable = [
        'dwelling_fire_id',
        'agencyID',
        'includedRisk',
        'risk_amount',
        'risk_prem',
        'coverageInc',
        'risk_premium',
        'colaps_included',
        'colaps_covpremium',
        'colaps_premium',
        'colaps_percentageIncrease',
        'colaps_perm',
        'loss_ass',
        'loss_assPrem',
        'lawCov_agg',
        'lawCov_incr',
        'lawCov_prem',
        'lawCov_limt',
        'lawCov_const',
        'ordIncluded',
        'lawCov_rebild',
        'derbs_included',
        'derbs_limit',
        'derbs_prem',
        'derbs_inc',
        'derbs_unit',
        'derbs_unitPrem',
        'earth_ded',
        'earth_terr',
        'earth_prem',
        'earth_dedAmount',
        'earth_type',
        'dreinIncluded',
        'dreinLimit',
        'dreinPrem',
        'massVaneerAmount',
        'windYes',
        'code_sec1_opts',
        'code_sec1_limit',
        'code_sec1_appl',
        'code_sec1_deduct',
        'code_sec1_prem',
        'code_sec1_opts2',
        'code_sec1_limit2',
        'code_sec1_appl2',
        'code_sec1_deduct2',
        'code_sec1_prem2',
        'desc_sec1_opt',
        'desc_sec1_limit',
        'desc_sec1_appl',
        'desc_sec1_type',
        'desc_sec1_opt2',
        'desc_sec1_limit2',
        'desc_sec1_appl2',
        'desc_sec1_type2',
        'desc_sec1_tree',
        'desc_sec1_y',
        'desc_sec1_tree2',
        'desc_sec1_y2',
        'code_sec2_opts',
        'code_sec2_limit',
        'code_sec2_appl',
        'code_sec2_deduct',
        'code_sec2_prem',
        'code_sec2_opts2',
        'code_sec2_limit2',
        'code_sec2_appl2',
        'code_sec2_deduct2',
        'code_sec2_prem2',
        'desc_sec2_opt',
        'desc_sec2_limit',
        'desc_sec2_appl',
        'desc_sec2_type',
        'desc_sec2_opt2',
        'desc_sec2_limit2',
        'desc_sec2_appl2',
        'desc_sec2_type2',
        'desc_sec2_tree',
        'desc_sec2_y',
        'desc_sec2_tree2',
        'desc_sec2_y2',
        'code_sec3_opts',
        'code_sec3_limit',
        'code_sec3_appl',
        'code_sec3_deduct',
        'code_sec3_prem',
        'code_sec3_opts2',
        'code_sec3_limit2',
        'code_sec3_appl2',
        'code_sec3_deduct2',
        'code_sec3_prem2',
        'desc_sec3_opt',
        'desc_sec3_limit',
        'desc_sec3_appl',
        'desc_sec3_type',
        'desc_sec3_opt2',
        'desc_sec3_limit2',
        'desc_sec3_appl2',
        'desc_sec3_type2',
        'desc_sec3_tree',
        'desc_sec3_y',
        'desc_sec3_tree2',
        'desc_sec3_y2',
        'code_sec4_opts',
        'code_sec4_limit',
        'code_sec4_appl',
        'code_sec4_deduct',
        'code_sec4_prem',
        'code_sec4_opts2',
        'code_sec4_limit2',
        'code_sec4_appl2',
        'code_sec4_deduct2',
        'code_sec4_prem2',
        'desc_sec4_opt',
        'desc_sec4_limit',
        'desc_sec4_appl',
        'desc_sec4_type',
        'desc_sec4_opt2',
        'desc_sec4_limit2',
        'desc_sec4_appl2',
        'desc_sec4_type2',
        'desc_sec4_tree',
        'desc_sec4_y',
        'desc_sec4_tree2',
        'desc_sec4_y2',
    ];

    public function dwellingFire(): BelongsTo
    {
        return $this->belongsTo(dwelling_fire_application::class, 'dwelling_fire_id');
    }
}
