<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Client;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

class InstallationBuilderRiskSection extends Model
{
    use  HasFactory;

    protected $table = 'installation_builder_risk_section';

    protected $fillable = [
            'client_id',
            'invoice_date',
            'agency_name',
            'career',
            'naic_code',
            'policy_number',
            'effective_date',
            'name_insured',
            'insallationCheck',
            'buildingRiskCheck',
            'limit_sing_loc',
            'limit_per_disaster',
            'limit_temp_loc',
            'transit_limit',
            'earthQuakeCheck',
            'earthQuakeSubLimit',
            'earthQuakeDeductible',
            'flood',
            'floodSubLimit',
            'floodDeductible',
            'otherCauseCheck',
            'otherCauseField',
            'otherCauseSubLim',
            'otherCauseDeductible',
            'specialCause',
            'specialCauseSubLim',
            'specialCauseDeductible',
            'broadCause',
            'basicSubLim',
            'broadDeductible',
            'operationTerritory',
            'pastMonth',
            'nextMonth',
            'resi_annualNum',
            'resi_duration',
            'resi_max',
            'resi_avg',
            'resi_maxCost',
            'resi_minCost',
            'resi_avgCost',
            'resi_materialPerc',
            'commercial_annualNum',
            'commercial_duration',
            'commercial_max',
            'commercial_avg',
            'commercial_maxCost',
            'commercial_minCost',
            'commercial_avgCost',
            'commercial_materialPerc',
            'accordCheck',
            'sec1_Lender',
            'sec1_LienHolder',
            'sec1_LossPayee',
            'sec1_otherCheck',
            'sec1_otherCheckField',
            'sec1_nameAddress',
            'sec1_rank',
            'sec1_referenceNo',
            'sec1_certificateReq',
            'sec1_loc',
            'sec1_building',
            'sec1_scheduledItem',
            'sec1_intrestOther',
            'sec1_description',
            'sec2_Lender',
            'sec2_LienHolder',
            'sec2_LossPayee',
            'sec2_otherCheck',
            'sec2_otherCheckField',
            'sec2_nameAddress',
            'sec2_rank',
            'sec2_referenceNo',
            'sec2_certificateReq',
            'sec2_loc',
            'sec2_building',
            'sec2_scheduledItem',
            'sec2_intrestOther',
            'sec2_description',
            'sec3_Lender',
            'sec3_LienHolder',
            'sec3_LossPayee',
            'sec3_otherCheck',
            'sec3_otherCheckField',
            'sec3_nameAddress',
            'sec3_rank',
            'sec3_referenceNo',
            'sec3_certificateReq',
            'sec3_loc',
            'sec3_building',
            'sec3_scheduledItem',
            'sec3_intrestOther',
            'sec3_description',
            'riggingHosting',
            'estimatePercentagRigging',
            'jobsiteSecurity',
            'remarks',
            'p2_limit_loc',
            'p2_limit_temp_loc',
            'p2_transit_limit',
            'p2_earthQuake',
            'p2_earthQuakeSubLim',
            'p2_earthQuakeDeductible',
            'p2_FLOOD',
            'p2_FLOODSubLim',
            'p2_FLOODDeductible',
            'p2_otherCauseCheck',
            'p2_otherCauseCheckField',
            'p2_otherCauseSubLim',
            'p2_otherCauseDeductible',
            'p2_Special',
            'p2_SpecialSubLim',
            'p2_SpecialDeductible',
            'p2_BROAD',
            'p2_BASIC',
            'p2_BASICDeductible',
            'p2_commencement',
            'p2_completion',
            'p2_contractAmount',
            'p2_ownerSupplied',
            'p2_jobSecurity',
            'p2_workedPerformed',
            'p2_insuredJobNumber',
            'p2_sec1_Lender',
            'p2_sec1_LienHolder',
            'p2_sec1_LossPayee',
            'p2_sec1_otherCheck',
            'p2_sec1_otherCheckField',
            'p2_sec1_nameAddress',
            'p2_sec1_rank',
            'p2_sec1_referenceNo',
            'p2_sec1_certificateReq',
            'p2_sec1_loc',
            'p2_sec1_building',
            'p2_sec1_scheduledItem',
            'p2_sec1_intrestOther',
            'p2_sec1_description',
            'p2_sec2_Lender',
            'p2_sec2_LienHolder',
            'p2_sec2_LossPayee',
            'p2_sec2_otherCheck',
            'p2_sec2_otherCheckField',
            'p2_sec2_nameAddress',
            'p2_sec2_rank',
            'p2_sec2_referenceNo',
            'p2_sec2_certificateReq',
            'p2_sec2_loc',
            'p2_sec2_building',
            'p2_sec2_scheduledItem',
            'p2_sec2_intrestOther',
            'p2_sec2_description',
            'p2_sec3_Lender',
            'p2_sec3_LienHolder',
            'p2_sec3_LossPayee',
            'p2_sec3_otherCheck',
            'p2_sec3_otherCheckField',
            'p2_sec3_nameAddress',
            'p2_sec3_rank',
            'p2_sec3_referenceNo',
            'p2_sec3_certificateReq',
            'p2_sec3_loc',
            'p2_sec3_building',
            'p2_sec3_scheduledItem',
            'p2_sec3_intrestOther',
            'p2_sec3_description',
            'P2_amountShipped',
            'P2_applicatsVehcles',
            'P2_contractorCarrier',
            'P2_distanceInvolved',
            'p2_riggingHosting',
            'p2_remarks',
            'agency_id',
            'P2_producerSignature',
            'P2_producerName',
            'P2_producerLicense',
            'P2_applicantSignature',
            'P2_applicationdate',
            'P2_nationalProducerNo',
            'created_by',
    ];


    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    // Relationship with Client
    public function client()
    {
        return $this->belongsTo(Client::class);
    }        
}
