<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

class PropertyPremisesSec extends Model
{
    use  HasFactory;

    protected $table = 'property_premises_sec';

    protected $fillable = [
        'property_id',
        'sec2_premises_no',
        'sec2_street_address',
        'sec2_building_no',
        'sec2_building_desc',
        'sec2_r1_sub_insure',
        'sec2_r1_amount',
        'sec2_r1_coins',
        'sec2_r1_valuation',
        'sec2_r1_cause_loss',
        'sec2_r1_inflation',
        'sec2_r1_ded',
        'sec2_r1_ded_type',
        'sec2_r1_blanket',
        'sec2_r1_forms',
        'sec2_r2_sub_insure',
        'sec2_r2_amount',
        'sec2_r2_coins',
        'sec2_r2_valuation',
        'sec2_r2_cause_loss',
        'sec2_r2_inflation',
        'sec2_r2_ded',
        'sec2_r2_ded_type',
        'sec2_r2_blanket',
        'sec2_r2_forms',
        'sec2_r3_sub_insure',
        'sec2_r3_amount',
        'sec2_r3_coins',
        'sec2_r3_valuation',
        'sec2_r3_cause_loss',
        'sec2_r3_inflation',
        'sec2_r3_ded',
        'sec2_r3_ded_type',
        'sec2_r3_blanket',
        'sec2_r3_forms',
        'sec2_r4_sub_insure',
        'sec2_r4_amount',
        'sec2_r4_coins',
        'sec2_r4_valuation',
        'sec2_r4_cause_loss',
        'sec2_r4_inflation',
        'sec2_r4_ded',
        'sec2_r4_ded_type',
        'sec2_r4_blanket',
        'sec2_r4_forms',
        'sec2_r5_sub_insure',
        'sec2_r5_amount',
        'sec2_r5_coins',
        'sec2_r5_valuation',
        'sec2_r5_cause_loss',
        'sec2_r5_inflation',
        'sec2_r5_ded',
        'sec2_r5_ded_type',
        'sec2_r5_blanket',
        'sec2_r5_forms',
        'sec2_business_income',
        'sec2_value_reporting',
        'sec2_spoilage',
        'sec2_property_coverageDes',
        'sec2_limit',
        'sec2_agreement',
        'sec2_breakdown',
        'sec2_power_outage',
        'sec2_selling_price',
        'sec2_deductable',
        'sec2_coverage_accept',
        'sec2_coverage_reject',
        'sec2_coverage_limit',
        'sec2_mine_accept',
        'sec2_mine_reject',
        'sec2_mine_limit',
        'sec2_propertyHistorical',
        'sec2_slidesStruct',
        'sec2_construction_ty',
        'sec2_distanceto',
        'sec2_fireState',
        'sec2_fire_district',
        'sec2_code_no',
        'sec2_protCl',
        'sec2_stories',
        'sec2_basm',
        'sec2_yrbuilt',
        'sec2_totalArea',
        'sec2_wiringYr',
        'sec2_plumbering',
        'sec2_roofingYr',
        'sec2_heating',
        'sec2_otherYR',
        'sec2_otherYRField',
        'sec2_resistive',
        'sec2_semi_resistive',
        'sec2_roofT_otherCheck',
        'sec2_roofT_otherCheckField',
        'sec2_headingSource',
        'sec2_dateInstalled',
        'sec2_primary_boiler',
        'sec2_primary_solidFuel',
        'sec2_primary_otherC',
        'sec2_primary_otherCF',
        'sec2_PrimarybolierPlace',
        'sec2_secondary_boiler',
        'sec2_secondary_solidFuel',
        'sec2_secondary_otherC',
        'sec2_secondary_otherCF',
        'sec2_secondarybolierPlace',
        'sec2_rightExp',
        'sec2_leftExp',
        'sec2_frontExp',
        'sec2_rearExp',
        'sec2_buglerAlarm',
        'sec2_certificate',
        'sec2_expirationDate',
        'sec2_centralSatation',
        'sec2_localGong',
        'sec2_withKeys',
        'sec2_burglerAlarmInstall',
        'sec2_extent',
        'sec2_grade',
        'sec2_watchman',
        'sec2_clockHourly',
        'sec2_otherCheckCH',
        'sec2_otherCheckCHF',
        'sec2_premisisFireProtect',
        'sec2_sprik',
        'sec2_fireAlarmManufacture',
        'sec2_CentralS',
        'sec2_localG',
        'acc2rdCheck',
        'sec2_lenderPay',
        'sec2_lossPayee',
        'sec2_mortgagee',
        'sec2_intrestOther',
        'sec2_intrestOtherField',
        'sec2_nameAddress',
        'sec2_rank',
        'sec2_evidence',
        'sec2_certificate_intrest',
        'sec2_referenceLoan',
        'sec2_location_interest',
        'sec2_building_interest',
        'sec2_itemClass_interest',
        'sec2_item_interest',
        'sec2_itemDescriptionInt'
    ];


     public function propertySection(): BelongsTo
    {
        return $this->belongsTo(PropertySection::class, 'property_id');
    }
}
