<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

class PropertyPremises extends Model
{
    use  HasFactory;

    protected $table = 'property_premises';

    protected $fillable = [
        'property_id',
        'sec1_premises_no',
        'sec1_street_address',
        'sec1_building_no',
        'sec1_building_desc',
        'sec1_r1_sub_insure',
        'sec1_r1_amount',
        'sec1_r1_coins',
        'sec1_r1_valuation',
        'sec1_r1_cause_loss',
        'sec1_r1_inflation',
        'sec1_r1_ded',
        'sec1_r1_ded_type',
        'sec1_r1_blanket',
        'sec1_r1_forms',
        'sec1_r2_sub_insure',
        'sec1_r2_amount',
        'sec1_r2_coins',
        'sec1_r2_valuation',
        'sec1_r2_cause_loss',
        'sec1_r2_inflation',
        'sec1_r2_ded',
        'sec1_r2_ded_type',
        'sec1_r2_blanket',
        'sec1_r2_forms',
        'sec1_r3_sub_insure',
        'sec1_r3_amount',
        'sec1_r3_coins',
        'sec1_r3_valuation',
        'sec1_r3_cause_loss',
        'sec1_r3_inflation',
        'sec1_r3_ded',
        'sec1_r3_ded_type',
        'sec1_r3_blanket',
        'sec1_r3_forms',
        'sec1_r4_sub_insure',
        'sec1_r4_amount',
        'sec1_r4_coins',
        'sec1_r4_valuation',
        'sec1_r4_cause_loss',
        'sec1_r4_inflation',
        'sec1_r4_ded',
        'sec1_r4_ded_type',
        'sec1_r4_blanket',
        'sec1_r4_forms',
        'sec1_r5_sub_insure',
        'sec1_r5_amount',
        'sec1_r5_coins',
        'sec1_r5_valuation',
        'sec1_r5_cause_loss',
        'sec1_r5_inflation',
        'sec1_r5_ded',
        'sec1_r5_ded_type',
        'sec1_r5_blanket',
        'sec1_r5_forms',
        'sec1_business_income',
        'sec1_value_reporting',
        'sec1_spoilage',
        'sec1_property_coverageDes',
        'sec1_limit',
        'sec1_agreement',
        'sec1_breakdown',
        'sec1_power_outage',
        'sec1_selling_price',
        'sec1_deductable',
        'sec1_coverage_accept',
        'sec1_coverage_reject',
        'sec1_coverage_limit',
        'sec1_mine_accept',
        'sec1_mine_reject',
        'sec1_mine_limit',
        'sec1_propertyHistorical',
        'sec1_slidesStruct',
        'sec1_construction_ty',
        'sec1_distanceto',
        'sec1_fireState',
        'sec1_fire_district',
        'sec1_code_no',
        'sec1_protCl',
        'sec1_stories',
        'sec1_basm',
        'sec1_yrbuilt',
        'sec1_totalArea',
        'sec1_wiringYr',
        'sec1_plumbering',
        'sec1_roofingYr',
        'sec1_heating',
        'sec1_otherYR',
        'sec1_otherYRField',
        'sec1_resistive',
        'sec1_semi_resistive',
        'sec1_roofT_otherCheck',
        'sec1_roofT_otherCheckField',
        'sec1_headingSource',
        'sec1_dateInstalled',
        'sec1_primary_boiler',
        'sec1_primary_solidFuel',
        'sec1_primary_otherC',
        'sec1_primary_otherCF',
        'sec1_PrimarybolierPlace',
        'sec1_secondary_boiler',
        'sec1_secondary_solidFuel',
        'sec1_secondary_otherC',
        'sec1_secondary_otherCF',
        'sec1_secondarybolierPlace',
        'sec1_rightExp',
        'sec1_leftExp',
        'sec1_frontExp',
        'sec1_rearExp',
        'sec1_buglerAlarm',
        'sec1_certificate',
        'sec1_expirationDate',
        'sec1_centralSatation',
        'sec1_localGong',
        'sec1_withKeys',
        'sec1_burglerAlarmInstall',
        'sec1_extent',
        'sec1_grade',
        'sec1_watchman',
        'sec1_clockHourly',
        'sec1_otherCheckCH',
        'sec1_otherCheckCHF',
        'sec1_premisisFireProtect',
        'sec1_sprik',
        'sec1_fireAlarmManufacture',
        'sec1_CentralS',
        'sec1_localG',
        'accordCheck',
        'sec1_lenderPay',
        'sec1_lossPayee',
        'sec1_mortgagee',
        'sec1_intrestOther',
        'sec1_intrestOtherField',
        'sec1_nameAddress',
        'sec1_rank',
        'sec1_evidence',
        'sec1_certificate_intrest',
        'sec1_referenceLoan',
        'sec1_location_interest',
        'sec1_building_interest',
        'sec1_itemClass_interest',
        'sec1_item_interest',
        'sec1_itemDescriptionInt',
    ];


     public function propertySection(): BelongsTo
    {
        return $this->belongsTo(PropertySection::class, 'property_id');
    }
}
